### ISSUE TITLE
parent pom is missing from repo

### ISSUE THREAD

**Issue by davidkarlsen** [springtestdbunit/spring-test-dbunit#111]
http://repo1.maven.org/maven2/com/github/springtestdbunit/spring-test-dbunit/parent does not exist

leading to:

```
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.github.springtestdbunit.parent:spring-test-dbunit-parent:jar:1.3.0 in https://myserver/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 21 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.github.springtestdbunit.parent:spring-test-dbunit-parent:jar:1.3.0 in https://myserver/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 23 more

```

**Comment by davidkarlsen** [comment]
Doh - cut and paste error on my side - sorry for the noise.
