### ISSUE TITLE
I am trying to use this for my test but it does not work.

### ISSUE THREAD

**Issue by xiaoshao** [springtestdbunit/spring-test-dbunit#126]
Here is my code.
https://github.com/xiaoshao/EmptyJavaProject/blob/master/src/test/java/com/db/UserDaoTest.java#L52

**Comment by xiaoshao** [comment]
Is there something I made mistake.

**Comment by djselzlein** [comment]
The link is broken

**Comment by xiaoshao** [comment]
sorry, here is the code https://github.com/xiaoshao/EmptyJavaProject/blob/master/src/test/java/com/db/VisitorDaoTest.java

It works well in my laptop, but failed in travis-ci. 

```
    org.dbunit.dataset.NoSuchTableException: Did not find table 'User' in schema 'null'
        at org.dbunit.database.DatabaseTableMetaData.<init>(DatabaseTableMetaData.java:146)
        at org.dbunit.database.DatabaseDataSet.getTableMetaData(DatabaseDataSet.java:316)
        at org.dbunit.operation.DeleteAllOperation.execute(DeleteAllOperation.java:109)
        at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
        at com.github.springtestdbunit.DbUnitRunner.setupOrTeardown(DbUnitRunner.java:183)
        at com.github.springtestdbunit.DbUnitRunner.beforeTestMethod(DbUnitRunner.java:75)
        at com.github.springtestdbunit.DbUnitTestExecutionListener.beforeTestMethod(DbUnitTestExecutionListener.java:185)
        at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:269)
        at org.springfra
```

**Comment by ppodgorsek** [comment]
Travis CI has been set up and works in a maintained repository: https://github.com/ppodgorsek/spring-test-dbunit
