### ISSUE TITLE
Did you tested it in travis ci?

### ISSUE THREAD

**Issue by xiaoshao** [springtestdbunit/spring-test-dbunit#129]
In travis CI, It always failed. But it woks well in my laptop

```
 org.dbunit.dataset.NoSuchTableException: Did not find table 'User' in schema 'null'
        at org.dbunit.database.DatabaseTableMetaData.<init>(DatabaseTableMetaData.java:146)
        at org.dbunit.database.DatabaseDataSet.getTableMetaData(DatabaseDataSet.java:316)
        at org.dbunit.operation.DeleteAllOperation.execute(DeleteAllOperation.java:109)
        at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
        at com.github.springtestdbunit.DbUnitRunner.setupOrTeardown(DbUnitRunner.java:183)
        at com.github.springtestdbunit.DbUnitRunner.beforeTestMethod(DbUnitRunner.java:75)
        at com.github.springtestdbunit.DbUnitTestExecutionListener.beforeTestMethod(DbUnitTestExecutionListener.java:185)
        at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:269)
        at 
```

My repo: https://github.com/xiaoshao/EmptyJavaProject
CI: https://travis-ci.org/xiaoshao/EmptyJavaProject

**Comment by ppodgorsek** [comment]
Travis CI has been set up and works in a maintained repository: https://github.com/ppodgorsek/spring-test-dbunit
