### ISSUE TITLE
Caught exception while allowing TestExecutionListener [com.github.springtestdbunit.TransactionDbUnitTestExecutionListener] ...

### ISSUE THREAD

**Issue by ndjordjevic** [springtestdbunit/spring-test-dbunit#41]
I have this simple junit test class:

```
@ContextConfiguration(locations = { "file:src/main/webapp/WEB-INF/spring/root-context.xml" })
@RunWith(SpringJUnit4ClassRunner.class)
@TestExecutionListeners({ DependencyInjectionTestExecutionListener.class,
    DirtiesContextTestExecutionListener.class,
    TransactionDbUnitTestExecutionListener.class,
    DbUnitTestExecutionListener.class })
@DatabaseSetup(value = "classpath:person-sample-data.xml", type = DatabaseOperation.CLEAN_INSERT)
@TransactionConfiguration
@DbUnitConfiguration(databaseConnection = "dataSource")
public class PersonTest {

@PersistenceContext
EntityManager em;

@Transactional
@Test
public void testSavePersonEM() {
    logger.info("--- testSavePersonEM ---");
    Person person = new Person("Vladimir", "Jankovic");
    person.setAddress("Starca Vujadina 27");
    person.setEmail("vjankovic@hotmail.com");

    logger.info("Before persist ...");

    // em.joinTransaction();
    em.persist(person);
    em.flush();

    logger.info("new id:" + person.getId());
}
```

}

I'm not sure if this is DBunit problem, Spring problem, or something is wrong else but I'm getting the following error:

<pre><code>2013-10-20 11:55:17,910 WARN [org.springframework.test.context.TestContextManager] - Caught exception while allowing TestExecutionListener [com.github.springtestdbunit.TransactionDbUnitTestExecutionListener@2c8c3540] to process 'after' execution for test: method [public void org.ndsys.dentalrec.domain.PersonTest.testLoadPersonWithoutRecords()], instance [org.ndsys.dentalrec.domain.PersonTest@28fc1399], exception [null]
org.springframework.transaction.TransactionSystemException: Could not roll back JPA transaction; nested exception is javax.persistence.PersistenceException: unexpected error when rollbacking
    at org.springframework.orm.jpa.JpaTransactionManager.doRollback(JpaTransactionManager.java:543) ~[spring-orm-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:846) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:823) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener$TransactionContext.endTransaction(TransactionalTestExecutionListener.java:588) ~[spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener.endTransaction(TransactionalTestExecutionListener.java:297) ~[spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener.afterTestMethod(TransactionalTestExecutionListener.java:192) ~[spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at com.github.springtestdbunit.TestExecutionListenerChain$4.call(TestExecutionListenerChain.java:100) ~[spring-test-dbunit-1.0.1.jar:na]
    at com.github.springtestdbunit.TestExecutionListenerChain.runChain(TestExecutionListenerChain.java:125) ~[spring-test-dbunit-1.0.1.jar:na]
    at com.github.springtestdbunit.TestExecutionListenerChain.backwards(TestExecutionListenerChain.java:118) ~[spring-test-dbunit-1.0.1.jar:na]
    at com.github.springtestdbunit.TestExecutionListenerChain.afterTestMethod(TestExecutionListenerChain.java:98) ~[spring-test-dbunit-1.0.1.jar:na]
    at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:395) ~[spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:91) [spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72) [spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231) [spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88) [spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71) [spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174) [spring-test-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50) [.cp/:na]
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467) [.cp/:na]
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683) [.cp/:na]
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390) [.cp/:na]
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197) [.cp/:na]
Caused by: javax.persistence.PersistenceException: unexpected error when rollbacking
    at org.hibernate.ejb.TransactionImpl.rollback(TransactionImpl.java:109) ~[hibernate-entitymanager-4.2.6.Final.jar:4.2.6.Final]
    at org.springframework.orm.jpa.JpaTransactionManager.doRollback(JpaTransactionManager.java:539) ~[spring-orm-3.1.4.RELEASE.jar:3.1.4.RELEASE]
    ... 29 common frames omitted
Caused by: org.hibernate.TransactionException: rollback failed
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.rollback(AbstractTransactionImpl.java:215) ~[hibernate-core-4.2.6.Final.jar:4.2.6.Final]
    at org.hibernate.ejb.TransactionImpl.rollback(TransactionImpl.java:106) ~[hibernate-entitymanager-4.2.6.Final.jar:4.2.6.Final]
    ... 30 common frames omitted
Caused by: org.hibernate.TransactionException: unable to rollback against JDBC connection
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doRollback(JdbcTransaction.java:167) ~[hibernate-core-4.2.6.Final.jar:4.2.6.Final]
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.rollback(AbstractTransactionImpl.java:209) ~[hibernate-core-4.2.6.Final.jar:4.2.6.Final]
    ... 31 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: connection does not exist
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.0.jar:2.3.0]
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.0.jar:2.3.0]
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.0.jar:2.3.0]
    at org.hsqldb.jdbc.JDBCUtil.connectionClosedException(Unknown Source) ~[hsqldb-2.3.0.jar:2.3.0]
    at org.hsqldb.jdbc.JDBCConnection.checkClosed(Unknown Source) ~[hsqldb-2.3.0.jar:2.3.0]
    at org.hsqldb.jdbc.JDBCConnection.rollback(Unknown Source) ~[hsqldb-2.3.0.jar:2.3.0]
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doRollback(JdbcTransaction.java:163) ~[hibernate-core-4.2.6.Final.jar:4.2.6.Final]
    ... 32 common frames omitted
Caused by: org.hsqldb.HsqlException: connection exception: connection does not exist
    at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.3.0.jar:2.3.0]
    at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.3.0.jar:2.3.0]
    ... 37 common frames omitted</code></pre>

**Comment by whitetower957** [comment]
but my jdk is 1.8,and spring jars are 4.26,There's still a mistake.
